audit_header: false
title: Palm Springs Real Estate Video Blog with -- CLIENT NAME --
description: >-
  Our mission at -- CLIENT BRAND -- is to be your best resource for Palm Springs
  real estate advice. Whether you are a buyer, seller, or investor, our team of
  professionals can answer any questions you might have about real estate. If
  you are looking to buy or sell a home, you can get all the information and the
  latest updates, tips, and tricks from The -- CLIENT BRAND --, your
  professional Palm Springs Real Estate Agents.
show_custom_links: true
custom_links:
  - title: Our Listings
    url: 'https://www.zillow.com/homes/for_sale/5673595_agent_list/0_mmm/'
  - title: About
    url: 'http://will.palmspringsarea.properties/agents/Will+Cook'
client:
  name: Will Cook
  title: Associate Broker/Team Leader of WILL COOK GROUP
  license_number: 'CA BRE #01879277'
  about_markdown: >-
   Ranked in the top 1% of all agents valley wide and named one of the Palm Springs Life Top Realtors for 2019, Will is an Associate Broker/Team Leader of the WILL COOK GROUP with Keller Williams Luxury Homes. A native of Baton Rouge, LA, Will attended graduate school in Boston and worked as a Medical Software Project Director focused on managing client expectations through sophisticated software implementation projects for many years. Will’s experience managing large scale projects in the corporate world has suited his transition to real estate over 17 years ago. Will’s mission has been to use integrity and accountability to exceed his client`s expectations. He has worked in the luxury markets of Boston and Miami Beach and has also owned his own real estate firm in Louisiana. Presently, Will is focused on the luxury markets of Palm Springs, Rancho Mirage, Palm Desert, Indian Wells and La Quinta. While most of Will’s experience has been marketing luxury homes and estates in gated and non-gated communities; he is equally as comfortable educating first time buyers and real estate investors. Will has been a multi-year, multi-million dollar producer and he understands the importance of acting as a focused and trusted adviser with each of his clients. He has been told that he is an effective communicator, skilled negotiator, and an excellent market resource for any buyer or seller. Will and his team understand what it takes to market and sell unique luxury homes and estates. He loves what he does and we think that makes a difference.
  market: Palm Springs
  brand: Will Cook Group
  brokerage: Keller Williams Luxury Homes
  address: '435 N Palm Canyon<br>Palm Springs, CA 92262'
  phone: 760-565-5714
  phone_type:
  phone2:
  phone2_type:
  email: Will@WillCookRealEstate.com
  url: http://WillCookGroup.com
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: >-
    http://will.palmspringsarea.properties/sell.php?town=city%3APalm+Springs&ppc=Video_Blog_Seller_Home_Value&addht=Video_Blog_Seller_Home_Value
  second_CTA_text: Home Search
  second_CTA_URL: >-
    http://will.palmspringsarea.properties/index.php?types[]=1&types[]=2&areas[]=city%3APalm+Springs&fbts=3108061&beds=0&baths=0&min=0&max=30000000&map=0&options[]=new&sortby=listings.listingdate+DESC&quick=1&ppc=VyralVideoBlog_Buyers&addht=VyralVideoBlog_Buyers#rslt
sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: What’s Your Palm Springs Home Worth?
    CTA_text: >-
      Are you thinking of selling your home or interested in learning about home
      prices in your neighborhood? We can help you.
    CTA_link_text: Free Home Value Report
    CTA_url: >-
      http://will.palmspringsarea.properties/sell.php?town=city%3APalm+Springs&ppc=Video_Blog_Seller_Home_Value&addht=Video_Blog_Seller_Home_Value
second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: Looking for a Palm Springs Home?
    CTA_text2: Search the entire MLS for your Palm Springs home.
    CTA_link_text2: Search the MLS
    CTA_url2: >-
      http://will.palmspringsarea.properties/index.php?types[]=1&types[]=2&areas[]=city%3APalm+Springs&fbts=3108061&beds=0&baths=0&min=0&max=30000000&map=0&options[]=new&sortby=listings.listingdate+DESC&quick=1&ppc=VyralVideoBlog_Buyers&addht=VyralVideoBlog_Buyers#rslt
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: 'http://fillmurray.com/200/200'
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: 'http://eyegoop.com'
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/WillCookGroup'
  linkedin_url: 'https://www.linkedin.com/in/willcookgroup'
  youtube_url: 'https://www.youtube.com/channel/UCQUFJyRnqS-69-vgsq1f-1g'
  twitter_url: 'http://www.twitter.com/willcookgroup'
  instagram_url:
  pinterest_url:
  zillow_url: 'http://www.zillow.com/profile/WillCookGroup/'
  trulia_url: >-
    http://www.trulia.com/profile/will-cook-agent-palm-springs-ca-365260/overview
  yelp_url: 'http://www.yelp.com/biz/will-cook-group-palm-springs-2'
  podcast_url: >-
    https://podcasts.apple.com/us/podcast/palm-springs-real-estate-podcast-with-will-cook/id1479470351
podcast:
  title: Palm Springs Real Estate Podcast with -- CLIENT NAME --
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the Palm
    Springs Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional
    Palm Springs Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in Palm Springs,
    home selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: '-- CLIENT NAME --'
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Palm Springs Real Estate Video Blog
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#52b0b3'
  theme_color: '#000000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
navbar_colors:
  border_bottom:
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#000000'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: 'rgba(0, 0, 0, 0)'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'